### ISSUE TITLE
cannot find the acl2020-commonsense-reasoning repository

### ISSUE THREAD

**Issue by chenxuantt** [SAP-samples/emnlp2021-attention-contrastive-learning#1]
When I tried to clone from acl2020-commonsense-reasoning repository, I found that the repository cannot found
![image](https://user-images.githubusercontent.com/49868348/144194720-6c14123a-e482-4ef8-872b-7b13e4f6970c.png)

![image](https://user-images.githubusercontent.com/49868348/144194627-767b0d20-68f9-4bd3-afdc-d2b4db9ed3da.png)

**Comment by TJKlein** [comment]
Thanks for spotting this. I should be the link of the current repository. "https://github.com/SAP-samples/emnlp2021-attention-contrastive-learning".
